"""Define the site's editable content and dynamic image slots.

Seed images are copied to the upload directory when the backend initializes,
so each slot has an initial image before an administrator replaces it.
"""

IMAGE_SLOTS = [
    # Fields: slot key, label, page, alt text, and seed filename in seed_images/.
    ("home-hero-education", "Homepage hero photo 1 (education)", "Home", "Education programme", "hero-education.jpg"),
    ("home-hero-health", "Homepage hero photo 2 (health)", "Home", "Health programme", "hero-health.jpg"),
    ("home-hero-livelihoods", "Homepage hero photo 3 (livelihoods)", "Home", "Livelihoods programme", "hero-livelihoods.jpg"),
    ("home-hero-solar", "Homepage hero photo 4 (solar)", "Home", "Solar energy programme", "hero-solar.jpg"),
    ("home-gallery-kalam", "Homepage gallery: Dr A.P.J. Abdul Kalam", "Home", "Courtesy meeting with Dr A.P.J. Abdul Kalam", "meeting-president-kalam.jpg"),
    ("home-gallery-patil", "Homepage gallery: Smt. Pratibha Devisingh Patil", "Home", "Courtesy meeting with Smt. Pratibha Devisingh Patil", "meeting-president-patil.jpg"),
    ("home-gallery-mukherjee", "Homepage gallery: Shri Pranab Mukherjee", "Home", "Courtesy meeting with Shri Pranab Mukherjee", "meeting-president-mukherjee.jpg"),
    ("home-gallery-kovind", "Homepage gallery: Shri Ram Nath Kovind", "Home", "Courtesy meeting with Shri Ram Nath Kovind", "meeting-president-kovind.jpg"),
    ("home-gallery-murmu", "Homepage gallery: Smt. Droupadi Murmu", "Home", "Courtesy meeting with Smt. Droupadi Murmu", "meeting-president-murmu.jpg"),
    ("home-gallery-pm", "Homepage gallery: Prime Minister", "Home", "Courtesy meeting with the Prime Minister", "meeting-pm.jpg"),
    ("site-logo", "Site logo (header & footer)", "Global", "Jagannath Foundation logo", "logo-mark.png"),
    ("about-founder-photo", "Founder photo (About page)", "About", "Dr Jagannath Patnaik", "jp.jpg"),
    ("team-jagannath-patnaik", "Dr Jagannath Patnaik", "Team", "Dr Jagannath Patnaik", "jp.jpg"),
    ("team-shrabani-patnaik", "Dr Shrabani Patnaik", "Team", "Dr Shrabani Patnaik", "sp.jpg"),
    ("team-prakriti-patnaik", "Adv. Prakriti Patnaik", "Team", "Adv. Prakriti Patnaik", "pp.jpg"),
    ("team-purushraj-patnaik", "Mr Purushraj Patnaik", "Team", "Mr Purushraj Patnaik", "pr.jpg"),
    ("team-samarendra-patra", "Er. Samarendra Patra", "Team", "Er. Samarendra Patra", "samarendra-patra.jpg"),
    ("team-sarita-patwal", "Ms Sarita Patwal", "Team", "Ms Sarita Patwal", "sarita-patwal.jpg"),
    ("team-prateek-nayak", "Adv. Prateek Nayak", "Team", "Adv. Prateek Nayak", "prateek-nayak.jpg"),
    ("team-reema-diddee", "CA Reema Diddee", "Team", "CA Reema Diddee", "reema-diddee.jpg"),
    ("team-lhamu-tshering-tamang", "Adv. Lhamu Tshering Tamang", "Team", "Adv. Lhamu Tshering Tamang", "lhamu-tshering-tamang.jpg"),
    ("advisor-pradeep-joshi", "Prof. (Dr.) Pradeep Kumar Joshi", "Team", "Prof. (Dr.) Pradeep Kumar Joshi", "advisor-pradeep-joshi.jpg"),
    ("advisor-gurbirpal-singh", "Lt Gen Gurbirpal Singh", "Team", "Lt Gen Gurbirpal Singh", "advisor-gurbirpal-singh.jpg"),
    ("advisor-op-singh", "Shri O.P. Singh", "Team", "Shri O.P. Singh", "advisor-op-singh.jpg"),
    ("advisor-ss-mantha", "Prof. (Dr.) S. S. Mantha", "Team", "Prof. (Dr.) S. S. Mantha", "advisor-ss-mantha.jpg"),
    ("advisor-avinash-khanna", "Dr. Avinash Rai Khanna", "Team", "Dr. Avinash Rai Khanna", "advisor-avinash-khanna.jpg"),
    ("advisor-subhash-chandra", "Shri Subhash Chandra", "Team", "Shri Subhash Chandra", "advisor-subhash-chandra.jpg"),
    ("advisor-ajay-misra", "Shri Ajay Misra", "Team", "Shri Ajay Misra", "advisor-ajay-misra.jpg"),
    ("advisor-ashok-tripathi", "Dr. Ashok Tripathi", "Team", "Dr. Ashok Tripathi", "advisor-ashok-tripathi.jpg"),
    ("advisor-viney-kapoor-mehra", "Prof. (Dr.) Viney Kapoor Mehra", "Team", "Prof. (Dr.) Viney Kapoor Mehra", "advisor-viney-kapoor-mehra.jpg"),
    ("advisor-parimal-vyas", "Prof. (Dr.) Parimal H. Vyas", "Team", "Prof. (Dr.) Parimal H. Vyas", "advisor-parimal-vyas.jpg"),
    ("advisor-raj-nath-yadava", "Prof. Raj Nath Yadava", "Team", "Prof. Raj Nath Yadava", "advisor-raj-nath-yadava.jpg"),
    ("advisor-manuel-freire-garabal", "Prof. Sir Manuel Freire-Garabal y Núñez", "Team", "Prof. Sir Manuel Freire-Garabal y Núñez", "advisor-manuel-freire-garabal.jpg"),
    ("advisor-murali-rao", "Dr. Murali Rao", "Team", "Dr. Murali Rao", "advisor-murali-rao.jpg"),
    ("advisor-martin-mongiello", "Prof. Martin C.J. Mongiello", "Team", "Prof. Martin C.J. Mongiello", "advisor-martin-mongiello.jpg"),
    ("advisor-ajay-singh", "Dr. Ajay Singh", "Team", "Dr. Ajay Singh", "advisor-ajay-singh.jpg"),
    ("advisor-anil-khaitan", "Shri Anil Khaitan", "Team", "Shri Anil Khaitan", "advisor-anil-khaitan.jpg"),
    ("advisor-diwakar-sukul", "Prof. (Dr.) Diwakar Sukul", "Team", "Prof. (Dr.) Diwakar Sukul", "advisor-diwakar-sukul.jpg"),
    ("advisor-ghanashyam-lal-das", "Prof. Dr. Ghanashyam Lal Das", "Team", "Prof. Dr. Ghanashyam Lal Das", "advisor-ghanashyam-lal-das.jpg"),
    ("gallery-cover", "Gallery page cover image", "Gallery", "Courtesy meeting with the Chief Minister of Sikkim", "meeting-cm-sikkim.jpg"),
    ("work-education", "Work page: Education & literacy", "Work", "Education and literacy programme", "hero-education.jpg"),
    ("work-health", "Work page: Health & family welfare", "Work", "Health and family welfare programme", "hero-health.jpg"),
    ("work-livelihoods", "Work page: Women's livelihoods", "Work", "Women's livelihoods programme", "hero-livelihoods.jpg"),
    ("work-solar", "Work page: Solar housing & clean energy", "Work", "Solar housing programme", "hero-solar.jpg"),

    # Add gallery entries here; the admin panel discovers them after restart.
    ("gallery-kalam", "Dr A.P.J. Abdul Kalam", "Gallery", "Courtesy meeting with Dr A.P.J. Abdul Kalam, 11th President of India", "meeting-president-kalam.jpg"),
    ("gallery-patil", "Smt. Pratibha Devisingh Patil", "Gallery", "Courtesy meeting with Smt. Pratibha Devisingh Patil, 12th President of India", "meeting-president-patil.jpg"),
    ("gallery-mukherjee", "Shri Pranab Mukherjee", "Gallery", "Courtesy meeting with Shri Pranab Mukherjee, 13th President of India", "meeting-president-mukherjee.jpg"),
    ("gallery-kovind", "Shri Ram Nath Kovind", "Gallery", "Courtesy meeting with Shri Ram Nath Kovind, 14th President of India", "meeting-president-kovind.jpg"),
    ("gallery-murmu", "Smt. Droupadi Murmu", "Gallery", "Courtesy meeting with Smt. Droupadi Murmu, 15th President of India", "meeting-president-murmu.jpg"),
    ("gallery-pm-modi", "Prime Minister Shri Narendra Modi", "Gallery", "Courtesy meeting with the Prime Minister", "meeting-pm.jpg"),
    ("gallery-manmohan-singh", "Dr Manmohan Singh", "Gallery", "Courtesy meeting with former Prime Minister Dr Manmohan Singh", "meeting-manmohan-singh.jpg"),
    ("gallery-vp-dhankhar", "Vice President Shri Jagdeep Dhankhar", "Gallery", "Courtesy meeting with the Vice President", "meeting-vp-dhankhar.jpg"),
    ("gallery-amit-shah", "Shri Amit Shah", "Gallery", "Courtesy meeting with Union Home Minister Shri Amit Shah", "meeting-amit-shah.jpg"),
    ("gallery-rajnath-singh", "Shri Rajnath Singh", "Gallery", "Courtesy meeting with Raksha Mantri Shri Rajnath Singh", "meeting-rajnath.jpg"),
    ("gallery-om-birla", "Shri Om Birla", "Gallery", "Courtesy meeting with Lok Sabha Speaker Shri Om Birla", "meeting-om-birla.jpg"),
    ("gallery-jp-nadda", "Shri J.P. Nadda", "Gallery", "Courtesy meeting with Shri J.P. Nadda", "meeting-jp-nadda.jpg"),
    ("gallery-dharmendra-pradhan", "Shri Dharmendra Pradhan", "Gallery", "Courtesy meeting with Union Minister Shri Dharmendra Pradhan", "meeting-dharmendra-pradhan.jpg"),
    ("gallery-anna-hazare", "Shri Anna Hazare", "Gallery", "Courtesy meeting with social activist Shri Anna Hazare", "meeting-anna-hazare.jpg"),
    ("gallery-sri-sri", "Sri Sri Ravi Shankar", "Gallery", "Courtesy meeting with Sri Sri Ravi Shankar", "meeting-sri-sri.jpg"),
    ("gallery-baba-ramdev", "Swami Ramdev", "Gallery", "Courtesy meeting with Swami Ramdev", "meeting-ramdev.jpg"),
    ("gallery-hemant-soren", "Shri Hemant Soren", "Gallery", "Courtesy meeting with Jharkhand CM Shri Hemant Soren", "meeting-hemant-soren.jpg"),
    ("gallery-cm-sikkim", "Chief Minister, Sikkim", "Gallery", "Courtesy meeting with the Chief Minister of Sikkim", "meeting-cm-sikkim.jpg"),
    ("gallery-governor-icfai", "Governor's visit, ICFAI University Sikkim", "Gallery", "Governor's visit at ICFAI University Sikkim", "meeting-governor-icfai.jpg"),
    ("gallery-bhutan-official", "Courtesy call, Bhutan", "Gallery", "Courtesy meeting with a Bhutanese official", "meeting-bhutan-official.jpg"),
    ("gallery-venkaiah-naidu", "Shri M. Venkaiah Naidu", "Gallery", "Courtesy meeting with former Vice President Shri M. Venkaiah Naidu", "meeting-venkaiah-naidu.jpg"),
]

# Additional photographs supplied in the jfcharity gallery collection.
# Fields: stable slug, display label, accessible description, and seed filename.
EXTRA_GALLERY_IMAGES = [
    ("arjun-ram-meghwal", "Courtesy meeting with Shri Arjun Ram Meghwal", "Courtesy meeting with Shri Arjun Ram Meghwal", "meeting-arjun-ram-meghwal.jpg"),
    ("ayodhya-group", "Community gathering in Ayodhya", "Community gathering in Ayodhya", "meeting-ayodhya-group.jpg"),
    ("baba-ramdev-2", "Meeting with Swami Ramdev", "Courtesy meeting with Swami Ramdev", "meeting-baba-ramdev-2.jpg"),
    ("bhutan-flag", "Courtesy meeting with Bhutanese representatives", "Courtesy meeting with Bhutanese representatives", "meeting-bhutan-flag.jpg"),
    ("bouquet-office-1", "Courtesy meeting and bouquet presentation", "Courtesy meeting and bouquet presentation", "meeting-bouquet-office-1.jpg"),
    ("bouquet-office-2", "Courtesy meeting and bouquet presentation", "Courtesy meeting and bouquet presentation", "meeting-bouquet-office-2.jpg"),
    ("bouquet-office-3", "Courtesy meeting and bouquet presentation", "Courtesy meeting and bouquet presentation", "meeting-bouquet-office-3.jpg"),
    ("chhattisgarh-assembly", "Visit to the Chhattisgarh Legislative Assembly", "Courtesy visit to the Chhattisgarh Legislative Assembly", "meeting-chhattisgarh-assembly.jpg"),
    ("cm-office-1", "Courtesy meeting at a Chief Minister's office", "Courtesy meeting at a Chief Minister's office", "meeting-cm-office-1.jpg"),
    ("cm-seated", "Meeting with a Chief Minister", "Courtesy meeting with a Chief Minister", "meeting-cm-seated.jpg"),
    ("cm-sikkim-blessing", "Blessings from the Chief Minister of Sikkim", "Receiving blessings from the Chief Minister of Sikkim", "meeting-cm-sikkim-blessing.jpg"),
    ("cm-uttarakhand", "Meeting with the Chief Minister of Uttarakhand", "Courtesy meeting with the Chief Minister of Uttarakhand", "meeting-cm-uttarakhand.jpg"),
    ("conference-group", "Conference gathering", "Group photograph at a conference", "meeting-conference-group.jpg"),
    ("dharmendra-pradhan-2", "Meeting with Shri Dharmendra Pradhan", "Courtesy meeting with Shri Dharmendra Pradhan", "meeting-dharmendra-pradhan-2.jpg"),
    ("embassy-thimphu", "Visit to the Embassy in Thimphu", "Courtesy visit to the Embassy in Thimphu", "meeting-embassy-thimphu.jpg"),
    ("felicitation-plaque", "Felicitation and plaque presentation", "Felicitation and presentation of a commemorative plaque", "meeting-felicitation-plaque.jpg"),
    ("goa-rajbhavan", "Visit to Goa Raj Bhavan", "Courtesy meeting at Goa Raj Bhavan", "meeting-goa-rajbhavan.jpg"),
    ("governor-bouquet", "Meeting with a Governor", "Courtesy meeting and bouquet presentation to a Governor", "meeting-governor-bouquet.jpg"),
    ("governor-cap", "Meeting with a Governor", "Courtesy meeting with a Governor", "meeting-governor-cap.jpg"),
    ("governor-flag", "Meeting with a Governor", "Courtesy meeting with a Governor", "meeting-governor-flag.jpg"),
    ("governor-flags", "Meeting with a Governor", "Courtesy meeting with a Governor", "meeting-governor-flags.jpg"),
    ("governor-seated", "Meeting with a Governor", "Courtesy meeting with a Governor", "meeting-governor-seated.jpg"),
    ("hemant-soren-2", "Meeting with Shri Hemant Soren", "Courtesy meeting with Shri Hemant Soren", "meeting-hemant-soren-2.jpg"),
    ("international-guest", "Meeting with an international guest", "Courtesy meeting with an international guest", "meeting-international-guest.jpg"),
    ("jitendra-singh", "Meeting with Dr Jitendra Singh", "Courtesy meeting with Dr Jitendra Singh", "meeting-jitendra-singh.jpg"),
    ("jp-nadda-2", "Meeting with Shri J.P. Nadda", "Courtesy meeting with Shri J.P. Nadda", "meeting-jp-nadda-2.jpg"),
    ("law-minister", "Meeting with the Union Law Minister", "Courtesy meeting with the Union Law Minister", "meeting-law-minister.jpg"),
    ("leader-seated-1", "Courtesy meeting with a public leader", "Courtesy meeting with a public leader", "meeting-leader-seated-1.jpg"),
    ("leader-sofa", "Courtesy meeting with a public leader", "Courtesy meeting with a public leader", "meeting-leader-sofa.jpg"),
    ("lok-bhavan-odisha", "Visit to Lok Bhavan, Odisha", "Courtesy visit to Lok Bhavan, Odisha", "meeting-lok-bhavan-odisha.jpg"),
    ("manohar-lal", "Meeting with Shri Manohar Lal", "Courtesy meeting with Shri Manohar Lal", "meeting-manohar-lal.jpg"),
    ("nepal-dignitary", "Meeting with a Nepalese dignitary", "Courtesy meeting with a Nepalese dignitary", "meeting-nepal-dignitary.jpg"),
    ("odisha-office-1", "Meeting in Odisha", "Courtesy meeting at an office in Odisha", "meeting-odisha-office-1.jpg"),
    ("odisha-office-2", "Meeting in Odisha", "Courtesy meeting at an office in Odisha", "meeting-odisha-office-2.jpg"),
    ("odisha", "Meeting in Odisha", "Courtesy meeting in Odisha", "meeting-odisha.jpg"),
    ("president-kovind-2", "Meeting with former President Shri Ram Nath Kovind", "Courtesy meeting with former President Shri Ram Nath Kovind", "meeting-president-kovind-2.jpg"),
    ("president-kovind-3", "Meeting with former President Shri Ram Nath Kovind", "Courtesy meeting with former President Shri Ram Nath Kovind", "meeting-president-kovind-3.jpg"),
    ("president-kovind-4", "Meeting with former President Shri Ram Nath Kovind", "Courtesy meeting with former President Shri Ram Nath Kovind", "meeting-president-kovind-4.jpg"),
    ("president-kovind-5", "Meeting with former President Shri Ram Nath Kovind", "Courtesy meeting with former President Shri Ram Nath Kovind", "meeting-president-kovind-5.jpg"),
    ("president-kovind-6", "Meeting with former President Shri Ram Nath Kovind", "Courtesy meeting with former President Shri Ram Nath Kovind", "meeting-president-kovind-6.jpg"),
    ("president-mukherjee-2", "Meeting with former President Shri Pranab Mukherjee", "Courtesy meeting with former President Shri Pranab Mukherjee", "meeting-president-mukherjee-2.jpg"),
    ("president-mukherjee-3", "Meeting with former President Shri Pranab Mukherjee", "Courtesy meeting with former President Shri Pranab Mukherjee", "meeting-president-mukherjee-3.jpg"),
    ("president-murmu-4", "Meeting with President Smt. Droupadi Murmu", "Courtesy meeting with President Smt. Droupadi Murmu", "meeting-president-murmu-4.jpg"),
    ("president-murmu-5", "Meeting with President Smt. Droupadi Murmu", "Courtesy meeting with President Smt. Droupadi Murmu", "meeting-president-murmu-5.jpg"),
    ("president-murmu-6", "Meeting with President Smt. Droupadi Murmu", "Courtesy meeting with President Smt. Droupadi Murmu", "meeting-president-murmu-6.jpg"),
    ("radhe-stole", "Felicitation with a ceremonial stole", "Felicitation with a ceremonial stole", "meeting-radhe-stole.jpg"),
    ("rajnath-2", "Meeting with Shri Rajnath Singh", "Courtesy meeting with Shri Rajnath Singh", "meeting-rajnath-2.jpg"),
    ("rbi", "Visit to the Reserve Bank of India", "Courtesy visit to the Reserve Bank of India", "meeting-rbi.jpg"),
    ("senior-leader-1", "Courtesy meeting with a senior public leader", "Courtesy meeting with a senior public leader", "meeting-senior-leader-1.jpg"),
    ("senior-leader-2", "Courtesy meeting with a senior public leader", "Courtesy meeting with a senior public leader", "meeting-senior-leader-2.jpg"),
    ("senior-statesman", "Meeting with a senior statesman", "Courtesy meeting with a senior statesman", "meeting-senior-statesman.jpg"),
    ("stole-governor", "Felicitation of a Governor", "Felicitation with a ceremonial stole for a Governor", "meeting-stole-governor.jpg"),
    ("union-minister-greet", "Meeting with a Union Minister", "Courtesy meeting with a Union Minister", "meeting-union-minister-greet.jpg"),
]

IMAGE_SLOTS.extend(
    (
        f"gallery-extra-{slug}",
        label,
        "Gallery",
        alt_text,
        filename,
    )
    for slug, label, alt_text, filename in EXTRA_GALLERY_IMAGES
)

SITE_CONTENT = [
    ("home_eyebrow", "Homepage eyebrow", "Home", "A public charitable trust · Across India"),
    ("home_title", "Homepage headline", "Home", "Building stronger communities, one lasting opportunity at a time."),
    ("home_intro", "Homepage introduction", "Home", "Jagannath Foundation works alongside communities through education, healthcare, livelihoods and clean energy, creating opportunities that last."),
    ("home_about_title", "Homepage about heading", "Home", "Dignity, opportunity and lasting change."),
    ("home_about_body", "Homepage about text", "Home", "Rooted in a belief that service to people is service to God, the Foundation works to widen access to education, strengthen family wellbeing and support communities to shape their own futures."),
    ("home_gallery_title", "Homepage gallery heading", "Home", "Partnerships built on respect."),
    ("home_gallery_body", "Homepage gallery introduction", "Home", "A selection of courtesy meetings and moments of shared purpose with leaders and friends of the Foundation."),
    ("about_heading", "About page introduction", "About", "A trust held for the public good."),
    ("about_intro", "About page introduction text", "About", "Jagannath Foundation is an irrevocable public charitable trust. Its income and property are applied only to its charitable objects, without private profit."),
    ("notice_title", "Noticeboard title", "Home", "News from the Foundation"),
    ("notice_body", "Noticeboard message", "Home", "We believe enduring change begins by listening to people and working alongside communities."),
]
